# Generated by Django 3.2 on 2023-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=149, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
