# Generated by Django 3.2 on 2023-06-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230621_0030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
